using FileManager.Core.Logging;
using FileManager.Core.Profiles;
using FileManager.Core.Routing;

namespace FileManager.Core.Jobs;

/// <summary>The outcome of a single Target write within a Job.</summary>
public sealed record TargetOutcome(string TargetRoot, string? FinalPath, TargetAction Action);

/// <summary>
/// A summary of one <see cref="JobEngine.ProcessFile"/> run: the final state plus enough detail to
/// explain it — per-Target outcomes, the deciding filter on a skip, the disposition taken, and the
/// log entries generated.
/// </summary>
public sealed record JobResult
{
    public required string JobId { get; init; }
    public required JobState State { get; init; }
    public required string SourcePath { get; init; }

    /// <summary>Per-Target results (empty when the Job was screened out or failed before distribution).</summary>
    public IReadOnlyList<TargetOutcome> Targets { get; init; } = Array.Empty<TargetOutcome>();

    /// <summary>When <see cref="State"/> is <see cref="JobState.Skipped"/>, the filter that rejected the file.</summary>
    public string? DecidingFilter { get; init; }

    /// <summary>The disposition applied to the source (null unless the Job reached Phase 6).</summary>
    public OnSuccess? Disposition { get; init; }

    /// <summary>Where the source ended up after disposition (archive/trash path), if applicable.</summary>
    public string? DispositionPath { get; init; }

    /// <summary>A human-readable reason when <see cref="State"/> is <see cref="JobState.Failed"/>.</summary>
    public string? FailureReason { get; init; }

    /// <summary>All log entries generated by the run (the sink receives a verbosity-filtered subset).</summary>
    public IReadOnlyList<JobLogEntry> Logs { get; init; } = Array.Empty<JobLogEntry>();
}
